# Generated by Django 6.1.1 on 2026-10-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_No', models.CharField(max_length=20)),
                ('Owner_Name', models.CharField(max_length=30)),
                ('Vehicle_Model', models.CharField(max_length=30)),
                ('Service_Date', models.DateField()),
                ('Phone', models.CharField(max_length=10)),
                ('Service_Type', models.CharField(max_length=30)),
                ('Amount', models.FloatField()),
                ('Kms_Run', models.IntegerField()),
                ('Compliant', models.TextField()),
                ('Last_Service_Date', models.DateField(null=True)),
                ('Engine_Oil_Type', models.CharField(max_length=30)),
            ],
        ),
    ]
