# Generated by Django 6.1.1 on 2026-10-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle_service',
            old_name='Phone',
            new_name='Phone_No',
        ),
        migrations.RemoveField(
            model_name='vehicle_service',
            name='Compliant',
        ),
        migrations.RemoveField(
            model_name='vehicle_service',
            name='Engine_Oil_Type',
        ),
    ]
